packages:
  - services/*
  - devtools/*
  # packages/* (shared contracts) arrives in Step 3

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@swc/core'
  - argon2
  - esbuild
  - msgpackr-extract
  - prisma
  - unrs-resolver

ignoredBuiltDependencies:
  - '@scarf/scarf'
